site_name: 'Multi Radio'
site_description: 'Documentação do projeto multi radio'
repo_name: 'BRKsReginaldo/multi-radio'
repo_url: 'https://github.com/BRKsReginaldo/multi-radio'
nav:
  - Introdução:
      - Introdução: index.md
      - Como Funciona: how-it-works.md
      - Solução de Problemas: troubleshooting.md
      - Desenvolvimento: development.md
  - Deploy:
      - Guia de Instalação: deployment/installation-guide.md
  - Guia do Usuario:
      - IAM: user-guide/iam.md
      - Websites: user-guide/websites.md
  - Engenharia de Software:
      - Objetivos: software-engineering/goals.md
      - Regras de Desenvolvimento: software-engineering/rules.md
      - Entidades Globais: software-engineering/entities.md
      - Entidades Locais: software-engineering/local-entities.md

theme:
  name: 'material'
  language: pt
  palette:
    primary: 'teal'
    accent: 'orange'
  feature:
    tabs: true
extra:
  search:
    language: 'pt, en'
  social:
    - type: github
      link: https://github.com/BRKsReginaldo/multi-radio
  manifest: 'https://brksreginaldo.github.io/multi-radio/manifest.json'
markdown_extensions:
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde